version: 0.0
os: linux
files:
  - source: index.html
    destination: /usr/share/nginx/html/
  - source: scorekeeper.js
    destination: /usr/share/nginx/html/
  - source: style.css
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: RemoveExistingFiles.sh
